# Generated by Django 3.2.6 on 2021-08-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('processor', models.FloatField()),
                ('monitor', models.FloatField()),
            ],
        ),
    ]
